export const languages = [
    { code: 'en', name: 'English', placeholder: 'Text will appear here' },
    { code: 'es', name: 'Spanish', placeholder: 'El texto aparecerá aquí' },
    { code: 'fr', name: 'French', placeholder: 'Le texte apparaîtra ici' },
    { code: 'de', name: 'German', placeholder: 'Text wird hier angezeigt' },
    { code: 'it', name: 'Italian', placeholder: 'Il testo apparirà qui' },
    { code: 'pt', name: 'Portuguese', placeholder: 'O texto aparecerá aqui' },
    { code: 'ru', name: 'Russian', placeholder: 'Текст появится здесь' },
    { code: 'zh', name: 'Chinese', placeholder: '文本将显示在这里' },
    { code: 'ja', name: 'Japanese', placeholder: 'テキストはここに表示されます' },
    { code: 'ko', name: 'Korean', placeholder: '텍스트가 여기에 표시됩니다' },
    { code: 'ar', name: 'Arabic', placeholder: 'سيظهر النص هنا' },
    { code: 'hi', name: 'Hindi', placeholder: 'पाठ यहाँ दिखाई देगा' },
    { code: 'bn', name: 'Bengali', placeholder: 'লেখাটি এখানে প্রদর্শিত হবে' },
    { code: 'ur', name: 'Urdu', placeholder: 'متن یہاں ظاہر ہوگا' },
    { code: 'th', name: 'Thai', placeholder: 'ข้อความจะปรากฏที่นี่' },
    { code: 'vi', name: 'Vietnamese', placeholder: 'Văn bản sẽ xuất hiện ở đây' },
    { code: 'ms', name: 'Malay', placeholder: 'Teks akan muncul di sini' },
    { code: 'sw', name: 'Swahili', placeholder: 'Maandishi yataonekana hapa' },
    { code: 'fa', name: 'Persian', placeholder: 'متن اینجا ظاهر می‌شود' },
    { code: 'tr', name: 'Turkish', placeholder: 'Metin burada görünecek' },
    { code: 'he', name: 'Hebrew', placeholder: 'הטקסט יופיע כאן' },
    { code: 'pl', name: 'Polish', placeholder: 'Tekst pojawi się tutaj' },
    { code: 'uk', name: 'Ukrainian', placeholder: 'Текст з\'явиться тут' },
    { code: 'ta', name: 'Tamil', placeholder: 'உரை இங்கு தோன்றும்' },
    { code: 'mr', name: 'Marathi', placeholder: 'मजकूर इथे दिसेल' },
    { code: 'te', name: 'Telugu', placeholder: 'పాఠ్యం ఇక్కడ కనిపిస్తుంది' },
    { code: 'kn', name: 'Kannada', placeholder: 'ಪಠ್ಯವು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ' },
    { code: 'gu', name: 'Gujarati', placeholder: 'ટેક્સ્ટ અહીં દેખાશે' },
    { code: 'ml', name: 'Malayalam', placeholder: 'ടെക്സ്റ്റ് ഇവിടെ പ്രത്യക്ഷപ്പെടും' },
    { code: 'ne', name: 'Nepali', placeholder: 'पाठ यहाँ देखा हुनेछ' },
    { code: 'si', name: 'Sinhala', placeholder: 'පෙළ මෙහි පෙනේ' },
    { code: 'no', name: 'Norwegian', placeholder: 'Teksten vil vises her' },
    { code: 'sv', name: 'Swedish', placeholder: 'Texten visas här' },
    { code: 'fi', name: 'Finnish', placeholder: 'Teksti näkyy täällä' },
    { code: 'da', name: 'Danish', placeholder: 'Teksten vises her' },
    { code: 'nl', name: 'Dutch', placeholder: 'Tekst verschijnt hier' },
    { code: 'el', name: 'Greek', placeholder: 'Το κείμενο θα εμφανιστεί εδώ' },
    { code: 'cs', name: 'Czech', placeholder: 'Text se zde objeví' },
    { code: 'ro', name: 'Romanian', placeholder: 'Textul va apărea aici' },
    { code: 'hu', name: 'Hungarian', placeholder: 'A szöveg itt fog megjelenni' },
    { code: 'sk', name: 'Slovak', placeholder: 'Text sa zobrazí tu' },
    { code: 'sr', name: 'Serbian', placeholder: 'Текст ће се појавити овде' },
    { code: 'bg', name: 'Bulgarian', placeholder: 'Текстът ще се появи тук' },
    { code: 'hr', name: 'Croatian', placeholder: 'Tekst će se pojaviti ovdje' },
    { code: 'is', name: 'Icelandic', placeholder: 'Textinn mun birtast hér' },
    { code: 'ga', name: 'Irish', placeholder: 'Beidh an téacs le feiceáil anseo' },
    { code: 'cy', name: 'Welsh', placeholder: 'Bydd y testun yn ymddangos yma' },
    { code: 'eo', name: 'Esperanto', placeholder: 'Teksto aperos ĉi tie' },
    { code: 'lb', name: 'Luxembourgish', placeholder: 'Den Text erschéngt hei' },
    { code: 'mt', name: 'Maltese', placeholder: 'It-test se jidher hawn' },
    { code: 'af', name: 'Afrikaans', placeholder: 'Teks sal hier verskyn' },
    { code: 'zu', name: 'Zulu', placeholder: 'Umbhalo uzovela lapha' },
    { code: 'xh', name: 'Xhosa', placeholder: 'Umbhalo uza kubonakala apha' },
    { code: 'st', name: 'Sesotho', placeholder: 'Mongolo o tla hlaha mona' },
    { code: 'en', name: 'English', placeholder: 'Text will appear here' },
  { code: 'hi', name: 'Hindi', placeholder: 'पाठ यहाँ दिखाई देगा' },
  { code: 'bn', name: 'Bengali', placeholder: 'লেখাটি এখানে প্রদর্শিত হবে' },
  { code: 'ta', name: 'Tamil', placeholder: 'உரை இங்கு தோன்றும்' },
  { code: 'te', name: 'Telugu', placeholder: 'పాఠ్యం ఇక్కడ కనిపిస్తుంది' },
  { code: 'mr', name: 'Marathi', placeholder: 'मजकूर इथे दिसेल' },
  { code: 'kn', name: 'Kannada', placeholder: 'ಪಠ್ಯವು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ' },
  { code: 'gu', name: 'Gujarati', placeholder: 'ટેક્સ્ટ અહીં દેખાશે' },
  { code: 'ml', name: 'Malayalam', placeholder: 'ടെക്സ്റ്റ് ഇവിടെ പ്രത്യക്ഷപ്പെടും' },
  { code: 'pa', name: 'Punjabi', placeholder: 'ਪਾਠ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗਾ' },
  { code: 'or', name: 'Odia', placeholder: 'ଲେଖା ଏଠାରେ ଦେଖାଯିବ' },
  { code: 'as', name: 'Assamese', placeholder: 'পাঠ ইয়াত দেখা যাব' },
  { code: 'maithili', name: 'Maithili', placeholder: 'पाठ इहाँ देखाएल जाएत' },
  { code: 'ne', name: 'Nepali', placeholder: 'पाठ यहाँ देखा हुनेछ' },
  { code: 'si', name: 'Sinhala', placeholder: 'පෙළ මෙහි පෙනේ' },
  { code: 'ur', name: 'Urdu', placeholder: 'متن یہاں ظاہر ہوگا' },
  { code: 'bh', name: 'Bhojpuri', placeholder: 'पाठ इहाँ देखा जाई' },
  { code: 'awa', name: 'Awadhi', placeholder: 'पाठ अइँजा देखा जाइ' },
  { code: 'kash', name: 'Kashmiri', placeholder: 'متن ایتھ ظاہر تہ گے' },
  { code: 'sant', name: 'Santali', placeholder: 'ᱞᱤᱠᱛ ᱢᱟᱢᱨᱟᱹ ᱯᱚᱱᱚᱲᱤᱛ' },
  { code: 'mni', name: 'Manipuri', placeholder: 'লেখা ইয়াতে প্রকাশ হব' },
  { code: 'kok', name: 'Konkani', placeholder: 'मजकूर इथं दिसतलो' },
  { code: 'sind', name: 'Sindhi', placeholder: 'متن هتي نظر ايندو' },
  { code: 'bodo', name: 'Bodo', placeholder: 'आंथि नोमा खबोन' },
  { code: 'doi', name: 'Dogri', placeholder: 'पाठ इथे दिखाई देगा' },
  { code: 'garo', name: 'Garo', placeholder: 'Chithi ha jagichoka' },
  { code: 'tulu', name: 'Tulu', placeholder: 'ಪಠ್ಯವು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ' },
  { code: 'lep', name: 'Lepcha', placeholder: 'ᰛᰩᰵᰛ ᰩ᰷ᰜ ᰣᰬᰦ ᰜᰵ᰸ᰵ' },
  { code: 'khasi', name: 'Khasi', placeholder: 'Ka kyntien kan paw hangne' },
  { code: 'mizo', name: 'Mizo', placeholder: 'Chhiar loh kan i hmu ang' },
  { code: 'sora', name: 'Sora', placeholder: 'ᱪᱟᱦ ᱩᱢᱩ ᱦᱚᱛ' },
  { code: 'tripuri', name: 'Tripuri', placeholder: 'লেখা ইয়াত প্ৰদৰ্শিত হ’ব' },
]